package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	cmd "downhill-api/cmd/api"
	"downhill-api/database"
	"downhill-api/graph/model"
	"encoding/json"
	"fmt"
	"strconv"
	"time"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.AuthPayload, error) {
	hashedPassword, err := cmd.HashPassword(input.Password)

	user := &database.User{
		Username: cmd.CreateUsername(input.Email, input.RegID),
		Password: hashedPassword,
		Email:    input.Email,
		RegID:    input.RegID,
	}

	if err := cmd.CheckPassword(user.Password); err != true {
		return nil, fmt.Errorf("invalid password: %v", err)
	}

	if err := cmd.CheckEmail(user.Email); err != true {
		return nil, fmt.Errorf("invalid email: %v", err)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	if err := database.DB.Create(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to create user: %v", err)
	}

	token, err := createToken(fmt.Sprintf("%d", user.ID))
	if err != nil {
		return nil, fmt.Errorf("failed to create token: %v", err)
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:       fmt.Sprintf("%d", user.ID),
			Username: user.Username,
		},
	}, nil
}

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (bool, error) {
	user := &database.User{}

	if err := database.DB.Where("username = ?", input.Username).First(user).Error; err != nil {
		return false, fmt.Errorf("user not found")
	}

	if !cmd.CheckPasswordHash(input.Password, user.Password) {
		return false, fmt.Errorf("invalid password")
	}

	token, err := createToken(fmt.Sprintf("%d", user.ID))
	if err != nil {
		return false, fmt.Errorf("failed to create token: %v", err)
	}

	ctx = context.WithValue(ctx, "authToken", token)
	return true, nil
}

// Logout is the resolver for the Logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	ctx = context.WithValue(ctx, "logout", true)
	return true, nil
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.CreateCompanyInput) (*model.Company, error) {
	company := &database.Company{
		CompanyName: input.CompanyName,
	}

	if err := database.DB.Create(&company).Error; err != nil {
		return nil, fmt.Errorf("failed to create company: %v", err)
	}

	return &model.Company{
		ID:          fmt.Sprintf("%d", company.ID),
		CompanyName: company.CompanyName,
	}, nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input model.CreateRoleInput) (*model.Role, error) {
	var year uint
	var cgpa float64
	var ctc float64
	var base float64

	if input.Year != nil {
		year = uint(*input.Year)
	}

	if input.Cgpa != nil {
		cgpa = *input.Cgpa
	}

	if input.Ctc != nil {
		ctc = *input.Ctc
	}

	if input.Base != nil {
		base = *input.Base
	}

	companyIDInt, err := strconv.Atoi(input.CompanyID)
	if err != nil {
		return nil, fmt.Errorf("invalid companyID")
	}

	role := &database.Role{
		RoleName:  *input.RoleName,
		Year:      year,
		CompanyID: uint(companyIDInt),
		OfferType: *input.OfferType,
		CGPA:      cgpa,
		Other:     *input.Other,
		CTC:       ctc,
		Base:      base,
	}

	if err := database.DB.Create(&role).Error; err != nil {
		return nil, fmt.Errorf("failed to create role: %v", err)
	}

	redisKey := fmt.Sprintf("role:%d", role.ID)

	roleData, err := json.Marshal(role)
	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, roleData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return &model.Role{
		ID:        fmt.Sprintf("%d", role.ID),
		RoleName:  strPtr(role.RoleName),
		Year:      int32Ptr(role.Year),
		CompanyID: fmt.Sprintf("%d", role.CompanyID),
		OfferType: strPtr(role.OfferType),
		Cgpa:      float64Ptr(role.CGPA),
		Other:     strPtr(role.Other),
		Ctc:       float64Ptr(role.CTC),
		Base:      float64Ptr(role.Base),
	}, nil
}

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input model.CreateQuestionInput) (*model.QuestionBank, error) {
	companyIDInt, err := strconv.Atoi(input.CompanyID)
	if err != nil {
		return nil, fmt.Errorf("invalid companyID")
	}

	if input.Question == nil {
		return nil, fmt.Errorf("question cannot be null")
	}

	question := &database.QuestionBank{
		Question:  *input.Question,
		CompanyID: uint(companyIDInt),
		Years:     uint(*input.Years),
	}

	if err := database.DB.Create(&question).Error; err != nil {
		return nil, fmt.Errorf("failed to create question: %v", err)
	}

	redisKey := fmt.Sprintf("question:%d", question.ID)

	questionData, err := json.Marshal(question)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, questionData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return &model.QuestionBank{
		ID:       fmt.Sprintf("%d", question.ID),
		Question: strPtr(question.Question),
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	companyIDInt, err := strconv.Atoi(input.CompanyID)
	if err != nil {
		return nil, fmt.Errorf("invalid companyID")
	}

	uuidInt, err := strconv.Atoi(input.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid uuid")
	}

	post := &database.Post{
		UserID:    uint(uuidInt),
		CompanyID: uint(companyIDInt),
		Title:     *input.Title,
		Content:   *input.Content,
	}

	if err := database.DB.Create(&post).Error; err != nil {
		return nil, fmt.Errorf("failed to create post: %v", err)
	}

	redisKey := fmt.Sprintf("post:%d", post.ID)

	postData, err := json.Marshal(post)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, postData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return &model.Post{
		ID:      fmt.Sprintf("%d", post.ID),
		Title:   strPtr(post.Title),
		Content: strPtr(post.Content),
	}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	post := &database.Post{}

	if err := database.DB.First(post, id).Error; err != nil {
		return false, fmt.Errorf("post not found: %v", err)
	}

	if err := database.DB.Delete(post).Error; err != nil {
		return false, fmt.Errorf("failed to delete post: %v", err)
	}

	redisKey := fmt.Sprintf(id)

	r.RedisClient.Del(ctx, redisKey)

	return true, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	postIDInt, err := strconv.Atoi(input.PostID)
	if err != nil {
		return nil, fmt.Errorf("invalid postID")
	}

	userIDInt, err := strconv.Atoi(input.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid userID")
	}

	comment := &database.Comment{
		Content: input.Content,
		PostID:  uint(postIDInt),
		UserID:  uint(userIDInt),
	}

	if err := database.DB.Create(&comment).Error; err != nil {
		return nil, fmt.Errorf("failed to create comment: %v", err)
	}

	r.RedisClient.Del(ctx, fmt.Sprintf("comments:post:%d", comment.PostID))

	return &model.Comment{
		ID:      fmt.Sprintf("%d", comment.ID),
		Content: strPtr(comment.Content),
		PostID:  fmt.Sprintf("%d", comment.PostID),
		UserID:  fmt.Sprintf("%d", comment.UserID),
	}, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	comment := &database.Comment{}

	if err := database.DB.First(comment, id).Error; err != nil {
		return false, fmt.Errorf("comment not found: %v", err)
	}

	if err := database.DB.Delete(comment).Error; err != nil {
		return false, fmt.Errorf("failed to delete comment: %v", err)
	}

	r.RedisClient.Del(ctx, fmt.Sprintf("comments:post:%d", comment.PostID))

	return true, nil
}

// GetAllCompanies is the resolver for the getAllCompanies field.
func (r *queryResolver) GetAllCompanies(ctx context.Context) ([]*model.Company, error) {
	if cachedCompanies, err := r.RedisClient.Get(ctx, "companies:all").Result(); err == nil {
		var companies []*model.Company
		if err := json.Unmarshal([]byte(cachedCompanies), &companies); err == nil {
			fmt.Println("Cache hit for companies:all")
			return companies, nil
		}
	}

	companies := []database.Company{}

	if err := database.DB.Find(&companies).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch companies: %v", err)
	}

	var result []*model.Company
	for _, company := range companies {
		result = append(result, &model.Company{
			ID:          fmt.Sprintf("%d", company.ID),
			CompanyName: company.CompanyName,
		})
	}

	redisKey := "companies:all"

	companiesData, err := json.Marshal(result)

	if err == nil {
		// Note: r.RedisClient.Set bhi ek error return karta hai,
		// usko silently ignore kar sakte ho ya log kar sakte ho.
		err = r.RedisClient.Set(ctx, redisKey, companiesData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return result, nil
}

// GetCompanyByID is the resolver for the getCompanyByID field.
func (r *queryResolver) GetCompanyByID(ctx context.Context, companyID string) (*model.Company, error) {
	redisKey := fmt.Sprintf("company:%s", companyID)

	if cachedCompany, err := r.RedisClient.Get(ctx, redisKey).Result(); err == nil {
		var company model.Company
		if err := json.Unmarshal([]byte(cachedCompany), &company); err == nil {
			return &company, nil
		}
	}

	dbCompany := &database.Company{}
	if err := database.DB.First(dbCompany, companyID).Error; err != nil {
		return nil, fmt.Errorf("company not found: %v", err)
	}

	company := model.Company{
		ID:          companyID,
		CompanyName: dbCompany.CompanyName,
	}

	if data, err := json.Marshal(company); err == nil {
		if err := r.RedisClient.Set(ctx, redisKey, data, 24*time.Hour).Err(); err != nil {
			fmt.Println("redis warning:", err)
		}
	}

	return &company, nil
}

// GetRolesByCompany is the resolver for the getRolesByCompany field.
func (r *queryResolver) GetRolesByCompany(ctx context.Context, companyID string) ([]*model.Role, error) {
	if cachedRoles, err := r.RedisClient.Get(ctx, fmt.Sprintf("roles:company:%s", companyID)).Result(); err == nil {
		var roles []*model.Role
		if err := json.Unmarshal([]byte(cachedRoles), &roles); err == nil {
			return roles, nil
		}
	}

	roles := []database.Role{}
	if err := database.DB.Where("company_id = ?", companyID).Find(&roles).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch roles: %v", err)
	}

	var result []*model.Role
	for _, role := range roles {
		result = append(result, &model.Role{
			ID:        fmt.Sprintf("%d", role.ID),
			RoleName:  strPtr(role.RoleName),
			Year:      int32Ptr(role.Year),
			CompanyID: fmt.Sprintf("%d", role.ID),
			OfferType: strPtr(role.OfferType),
			Cgpa:      float64Ptr(role.CGPA),
			Other:     strPtr(role.Other),
			Ctc:       float64Ptr(role.CTC),
			Base:      float64Ptr(role.Base),
		})
	}

	redisKey := fmt.Sprintf("roles:company:%s", companyID)

	rolesData, err := json.Marshal(result)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, rolesData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return result, nil
}

// GetQuestionsByCompany is the resolver for the getQuestionsByCompany field.
func (r *queryResolver) GetQuestionsByCompany(ctx context.Context, companyID string) ([]*model.QuestionBank, error) {
	if cachedQuestions, err := r.RedisClient.Get(ctx, fmt.Sprintf("questions:company:%s", companyID)).Result(); err == nil {
		var questions []*model.QuestionBank
		if err := json.Unmarshal([]byte(cachedQuestions), &questions); err == nil {
			return questions, nil
		}
	}

	questions := []database.QuestionBank{}
	if err := database.DB.Where("company_id = ?", companyID).Find(&questions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch questions: %v", err)
	}

	var result []*model.QuestionBank
	for _, question := range questions {
		result = append(result, &model.QuestionBank{
			ID:       fmt.Sprintf("%d", question.ID),
			Question: strPtr(question.Question),
		})
	}

	redisKey := fmt.Sprintf("questions:company:%s", companyID)

	questionsData, err := json.Marshal(result)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, questionsData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return result, nil
}

// GetPost is the resolver for the getPost field.
func (r *queryResolver) GetPost(ctx context.Context, id string) (*model.Post, error) {
	if cachedPost, err := r.RedisClient.Get(ctx, fmt.Sprintf(id)).Result(); err == nil {
		var post *model.Post
		if err := json.Unmarshal([]byte(cachedPost), &post); err == nil {
			return post, nil
		}
	}

	post := &database.Post{}

	if err := database.DB.First(post, id).Error; err != nil {
		return nil, fmt.Errorf("post not found: %v", err)
	}

	redisKey := fmt.Sprintf(id)

	postData, err := json.Marshal(post)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, postData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return &model.Post{
		ID:      fmt.Sprintf("%d", post.ID),
		Title:   strPtr(post.Title),
		Content: strPtr(post.Content),
	}, nil
}

// GetPostByCompany is the resolver for the getPostByCompany field.
func (r *queryResolver) GetPostByCompany(ctx context.Context, companyID string) ([]*model.Post, error) {
	if cachedCompanyPosts, err := r.RedisClient.Get(ctx, "posts:company").Result(); err == nil {
		var posts []*model.Post
		if err := json.Unmarshal([]byte(cachedCompanyPosts), &posts); err == nil {
			return posts, nil
		}
	}

	var posts []database.Post

	if err := database.DB.Where("company_id = ?", companyID).Find(&posts).Error; err != nil {
		return nil, err
	}

	var result []*model.Post

	for _, post := range posts {
		result = append(result, &model.Post{
			ID:      fmt.Sprintf("%d", post.ID),
			Title:   strPtr(post.Title),
			Content: strPtr(post.Content),
		})
	}

	redisKey := "posts:company"

	postsData, err := json.Marshal(result)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, postsData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return result, nil
}

// GetAllPosts is the resolver for the getAllPosts field.
func (r *queryResolver) GetAllPosts(ctx context.Context) ([]*model.Post, error) {
	if cachedPosts, err := r.RedisClient.Get(ctx, "posts:all").Result(); err == nil {
		var posts []*model.Post
		if err := json.Unmarshal([]byte(cachedPosts), &posts); err == nil {
			return posts, nil
		}
	}

	posts := []database.Post{}
	if err := database.DB.Find(&posts).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch posts: %v", err)
	}

	var result []*model.Post
	for _, post := range posts {
		result = append(result, &model.Post{
			ID:      fmt.Sprintf("%d", post.ID),
			Title:   strPtr(post.Title),
			Content: strPtr(post.Content),
		})
	}

	redisKey := "posts:all"

	postsData, err := json.Marshal(result)

	if err == nil {
		err = r.RedisClient.Set(ctx, redisKey, postsData, 24*time.Hour).Err()
		if err != nil {
			fmt.Println(err)
		}
	}

	return result, nil
}

// GetCommentsByPost is the resolver for the getCommentsByPost field.
func (r *queryResolver) GetCommentsByPost(ctx context.Context, postID string) ([]*model.Comment, error) {
	redisKey := fmt.Sprintf("comments:post:%s", postID)

	if cached, err := r.RedisClient.Get(ctx, redisKey).Result(); err == nil {
		var comments []*model.Comment
		if err := json.Unmarshal([]byte(cached), &comments); err == nil {
			return comments, nil
		}
	}

	comments := []database.Comment{}
	if err := database.DB.Where("post_id = ?", postID).Find(&comments).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch comments: %v", err)
	}

	var result []*model.Comment
	for _, c := range comments {
		result = append(result, &model.Comment{
			ID:      fmt.Sprintf("%d", c.ID),
			Content: strPtr(c.Content),
			PostID:  fmt.Sprintf("%d", c.PostID),
			UserID:  fmt.Sprintf("%d", c.UserID),
		})
	}

	if data, err := json.Marshal(result); err == nil {
		r.RedisClient.Set(ctx, redisKey, data, 24*time.Hour)
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
